### ISSUE TITLE
[Spike] Multiplier for Vault shares

### ISSUE THREAD

**Issue by credbull** [credbull/credbull-defi#3]
Spike ability to apply some factor on the shares owned in a Vault.  

For example: some Share Owners receive 1:1 shares to assets, other Share owners receive 2:1.

**Comment by pasviegas** [comment]
I see 2 possible approaches for tiered staking:
- Have separate vaults for each tier and a master contract that manages them (in a poor man tier system we could even discard the master contract and just have 3 vaults that can only be accessed if some criteria is fulfilled).
- Tracking stakes and deposit dates to distribute the funds correctly according to the user tier whenever a deposit happens.

An example of a contract in the wild that does something similar:
https://github.com/envoynetwork/staking-contract-v2/blob/main/Readme.md
https://github.com/envoynetwork/staking-contract-v2/blob/main/contracts/contracts/EnvoyStaking.sol

**Comment by pasviegas** [comment]
https://github.com/credbull/credbull-defi/tree/main/packages/gnosis-timelock
