### ISSUE TITLE
Confirm if Operator key required in  api/.env.local.sample

### ISSUE THREAD

**Issue by lucasia** [credbull/credbull-defi#36]
hi @jplodge-pro - did you mean to also remove the Operator key?  i'm still investigating, but what i found is VaultFactory.createVaults needs to be called by the VaultFactory operator.  this is not the same as the Deployer.

_Originally posted by @lucasia in https://github.com/credbull/credbull-defi/pull/33#discussion_r1593901697_

**Comment by jplodge-pro** [comment]
I conducted a global search for the removed key, `ETHERS_OPERATOR_PRIVATE_KEY`, and found **no** instances of it anywhere. The other `ETHERS_*_PRIVATE_KEY` values are present (GitHub Actions config, local sample config and 1 test spec). This leads me to confirm that it is not required.
