### ISSUE TITLE
SDK arguments require 4 params 

### ISSUE THREAD

**Issue by lucasia** [credbull/credbull-defi#55]
does this work still if the SDK needs a user/password?

_Originally posted by @lucasia in https://github.com/credbull/credbull-defi/pull/52#discussion_r1632046039_

also failing here: https://github.com/credbull/credbull-defi/actions/runs/9428946961/job/25974801358

**Comment by jplodge-pro** [comment]
This failure is me not propagating an SDK change I made. I will fix asap.

Also, as discussed in this [PR](https://github.com/credbull/credbull-defi/pull/52), I will alter the SDK to allow username/password OR access token at construction. We also discussed that all SDK ops should go through the API, as that is the function of the SDK. This means the Signer requirement will be removed.

**Comment by jplodge-pro** [comment]
`sdk` and `ops` have been nominally "fixed". The aforementioned unpropagated change is now propagated and that issue should be resolved.

That said, the `sdk` concept is still in flux, but there are discussions to broaden it's capabilities and usage (i.e. `app` would also use the `sdk` for most/all operations). 

Still I am closing this Bug as resolved, in the spirit in which it was raised.
