### ISSUE TITLE
Update contracts/lib dependencies to LTS version

### ISSUE THREAD

**Issue by lucasia** [credbull/credbull-defi#65]
- [x] OpenZeppelin
- [x] Either update Foundry or Confirm no dependencies on Prod contracts on Foundry

**Comment by jplodge-pro** [comment]
What about our contracts' Solidity Version? And our `solc` version?

**Comment by jplodge-pro** [comment]
**CONFIRMED**: No production code dependency on foundry.

**Comment by jplodge-pro** [comment]
Ok, going back to basics (deleted my workspace N times!), our `main` has `std-forge` at `1.8.2` and `openzeppellin/contracts` at `5.0.1`. I will update both using `forge update` and will get the build working again. There are no 'deployed contracts' concerns for upgrading to the latest OpenZeppellin library.

**Comment by jplodge-pro** [comment]
Resolved by https://github.com/credbull/credbull-defi/pull/78
