### ISSUE TITLE
[Spike] TS/JS to Services Integration

### ISSUE THREAD

**Issue by credbull** [credbull/credbull-defi#8]
DEFI heavy use of Typescript/Javascript (e.g. ethers.js, Safe SDK).  Typescript is still Javascript runtime, and not my preference for service layer.

Check options for TS/JS to KotlinJVM.  
- Spike TS/JS to Kotlin over: http, websockets, or message bus
- Check for TS/JS Alternatives such as https://github.com/web3j/web3j for blockchain comms

**Comment by lucasia** [comment]
No longer required.  We will use TS/JS runtime.
